import pyperclip

class UsersData:
    '''
    Class that holds account and password data for the users
    '''
    data_list = []
    def __init__(self,ident,data_id,account,acc_key):
        self.ident = ident
        self.data_id = data_id
        self.account = account
        self.acc_key = acc_key

    def add_password(self):
        '''
        creating a method that creates the username and password
        '''
        UsersData.data_list.append(self)

    @classmethod
    def display_data(cls,number,count):
        '''
        display all passwords generated by the user
        '''
        for password in cls.data_list:
            if password.ident == number:
                if password.data_id == count:
                    return password

    @classmethod
    def existing_data(cls,number):
        '''
        Checks if data exists in the profile
        '''
        for data in cls.data_list:
            if data.ident == number:
                return True
        return False

    @classmethod
    def copy_password(cls,number,count):
        found_password = UsersData.display_data(number,count)
        pyperclip.copy(found_password.acc_key)